# Generated by Django 5.0.6 on 2024-05-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sepomex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_codigo', models.CharField(max_length=5)),
                ('d_asenta', models.CharField(max_length=100)),
                ('d_tipo_asenta', models.CharField(max_length=100)),
                ('D_mnpio', models.CharField(max_length=100)),
                ('d_estado', models.CharField(max_length=100)),
                ('d_ciudad', models.CharField(max_length=100)),
                ('d_CP', models.CharField(max_length=5)),
                ('c_estado', models.CharField(max_length=2)),
                ('c_oficina', models.CharField(max_length=5)),
                ('c_CP', models.CharField(max_length=1)),
                ('c_tipo_asenta', models.CharField(max_length=2)),
                ('c_mnpio', models.CharField(max_length=4)),
                ('id_asenta_cpcons', models.CharField(max_length=4)),
                ('d_zona', models.CharField(max_length=50)),
                ('c_cve_ciudad', models.CharField(max_length=4)),
            ],
        ),
    ]
