# Generated by Django 5.0.6 on 2024-05-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_sepomex'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
