# Generated by Django 4.2 on 2024-04-08 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_propiedad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='fechaa_publicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
