# Generated by Django 5.0.6 on 2024-05-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_propiedad_ciudad_propiedad_codigo_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='imagenes_360',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='asentamiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_principal',
            field=models.ImageField(upload_to='propiedades/'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='num_baños',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='num_habitaciones',
            field=models.IntegerField(),
        ),
    ]
