# Generated by Django 4.2 on 2024-04-08 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_propiedad_fechaa_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='fechaa_publicacion',
            new_name='fecha_publicacion',
        ),
    ]
