# Generated by Django 5.0.6 on 2024-05-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_propiedad_validado'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='num_estacionamientos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.CharField(choices=[('TE', 'Terreno'), ('CA', 'Casa'), ('DE', 'Departamento')], default='CA', max_length=2),
        ),
    ]
