# Generated by Django 4.2 on 2024-04-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuhogar360',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
