# Generated by Django 4.2 on 2024-04-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tuhogar360_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuhogar360',
            name='is_usuarioTuHogar360',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tuhogar360',
            name='is_vendedorTuHogar360',
            field=models.BooleanField(default=False),
        ),
    ]
